import type { Metadata } from "next";
import { Inter, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/lib/lenis";
import Navbar from "@/components/layout/Navbar";
import { ThemeProvider } from "@/components/themeProvider";

const barlowCondensed = Barlow_Condensed({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-barlow-condensed",
});

const inter = Inter({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang="en"
			className={`${inter.className} ${barlowCondensed.variable} h-full antialiased`}
		>
			<ReactLenis root>
				<body
					suppressContentEditableWarning
					className="min-h-full flex flex-col bg-black text-white"
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<Navbar />
						{children}
					</ThemeProvider>
				</body>
			</ReactLenis>
		</html>
	);
}
