import type { Metadata } from "next";
import { Geist, Geist_Mono, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/lib/lenis";

const barlowCondensed = Barlow_Condensed({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-barlow-condensed",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} ${barlowCondensed.className} h-full antialiased`}
		>
			<ReactLenis root>
				<body
					suppressContentEditableWarning
					className="min-h-full flex flex-col bg-black text-white"
				>
					{children}
				</body>
			</ReactLenis>
		</html>
	);
}
